const API = 'https://api.dothiscoach.com/api/partners';
const $ = (id) => document.getElementById(id);
const money = (cents) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((Number(cents)||0)/100);
const publicView=$('public-view'),dashboard=$('dashboard-view'),sessionAction=$('session-action');

function switchPanel(name){document.querySelectorAll('.tab').forEach((tab)=>{const active=tab.dataset.panel===name;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active))});document.querySelectorAll('.form-panel').forEach((panel)=>panel.classList.toggle('active',panel.id===`${name}-form`));}
document.querySelectorAll('.tab').forEach((tab)=>tab.addEventListener('click',()=>switchPanel(tab.dataset.panel)));
sessionAction.addEventListener('click',async()=>{if(sessionAction.dataset.signedIn==='true'){await fetch(`${API}/logout`,{method:'POST',credentials:'include'}).catch(()=>{});location.reload();return}switchPanel('login');$('login-form').scrollIntoView({behavior:'smooth',block:'center'})});

async function api(path,init={}){const response=await fetch(`${API}${path}`,{...init,credentials:'include',headers:{Accept:'application/json','Content-Type':'application/json',...(init.headers||{})}});const json=await response.json().catch(()=>null);if(!response.ok||!json?.success)throw new Error(json?.error||`Request failed (${response.status})`);return json.data;}
function submitForm(formId,path,messageId){const form=$(formId);form.addEventListener('submit',async(event)=>{event.preventDefault();const button=form.querySelector('button[type="submit"]');const message=$(messageId);message.textContent='';button.disabled=true;const values=Object.fromEntries(new FormData(form));if('acceptedTerms'in values)values.acceptedTerms=true;try{renderDashboard(await api(path,{method:'POST',body:JSON.stringify(values)}))}catch(error){message.textContent=error.message}finally{button.disabled=false}})}
submitForm('apply-form','/signup','apply-message');submitForm('login-form','/login','login-message');

function renderDashboard(data){publicView.classList.add('hidden');dashboard.classList.remove('hidden');sessionAction.textContent='Sign out';sessionAction.dataset.signedIn='true';$('welcome-title').textContent=`Welcome, ${data.username}.`;$('partner-status').textContent=data.status;$('partner-status').className=`status ${data.status}`;$('partner-code').textContent=data.code||data.preferredCode||'Reserved';$('subscriber-count').textContent=data.referredSubscribers||0;$('active-count').textContent=data.activeSubscribers||0;$('pending-earnings').textContent=money((data.pendingEarningsCents||0)+(data.approvedEarningsCents||0));$('paid-earnings').textContent=money(data.paidEarningsCents);const status={pending:'Application received. We will review your profile and requested code.',approved:data.codeStatus==='active'?'Your code is active. Share it with clear partner disclosure.':'You are approved. Your App Store code is being prepared.',rejected:`Application not approved${data.rejectionReason?`: ${data.rejectionReason}`:'.'}`,suspended:'This partner account is paused.'};$('status-copy').textContent=status[data.status]||'';$('code-card').classList.toggle('hidden',data.status!=='approved');window.scrollTo({top:0,behavior:'smooth'})}
$('copy-code').addEventListener('click',async()=>{await navigator.clipboard.writeText($('partner-code').textContent);$('copy-code').textContent='Copied';setTimeout(()=>$('copy-code').textContent='Copy code',1600)});
api('/session').then(renderDashboard).catch(()=>{});
